### ISSUE TITLE
About 5-shot experiment

### ISSUE THREAD

**Issue by SSSKYue** [AhmetSencan/MaskSplit-Self-supervised-Meta-learning-for-Few-shot-Semantic-Segmentation#4]
Hi, thanks for your great and creative work! There are some questions I'm curious about. As is shown in your paper, you only report 1-shot segmentation results in all experiments. However, 5-shot evaluation is also important for few-shot segmentation task. I wonder if your model can train or inference under the 5-shot setting？

Thank you very much.

**Comment by AhmetSencan** [comment]
Hi @SSSKYue, 
First of all, sorry for this late reply. I was going through my finals for the past few weeks. To answer your question, In its current state it can not train under the 5-shot setting. But it is definitely possible and we are currently working on some follow up work to extend our idea to 5-shot setting.

**Comment by sercanamac** [comment]
Hi @SSSKYue,
You are right. For 5-shot results you can try taking average of 5 predictions with 5 different support images.
